"""Generate the SIMULATED sample datasets used by ClearWay.

Nothing in the CSV files this script writes is a real observation. The values
are deterministic pseudo-random numbers, generated so that the scoring engine
and the missing-data handling can be demonstrated without pretending to have
municipal lighting or incident data.

Run from the repository root:

    python data/generate_sample_data.py

The output is committed to the repository so the demo behaves identically on
every machine and does not depend on the machine's random state.

The demonstration region is defined in src/data.py so the datasets and the
lookup logic can never drift apart.
"""

import csv
import random
import sys
from datetime import date, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from src.data import DEMO_REGION  # noqa: E402  (path set up above)

DATA_DIR = Path(__file__).resolve().parent

REGION_MIN_LAT = DEMO_REGION["min_lat"]
REGION_MAX_LAT = DEMO_REGION["max_lat"]
REGION_MIN_LON = DEMO_REGION["min_lon"]
REGION_MAX_LON = DEMO_REGION["max_lon"]

LIGHTING_GRID_STEP = 0.005
HAZARD_GRID_STEP = 0.008

LIGHTING_STATUSES = ["lit", "partial", "unlit"]
LIGHTING_WEIGHTS = [0.60, 0.25, 0.15]

HAZARD_CATEGORIES = [
    "poor_lighting",
    "uneven_footpath",
    "no_footpath",
    "stray_animals",
    "isolated_stretch",
    "unsafe_crossing",
]

# Roughly 35% of grid cells carry a hazard record.
HAZARD_PRESENCE_PROBABILITY = 0.35

SIMULATED_SOURCE = (
    "ClearWay simulated sample data - NOT a real observation, "
    "generated by data/generate_sample_data.py"
)

TODAY = date(2026, 10, 10)


def _grid(min_value, max_value, step):
    count = int(round((max_value - min_value) / step)) + 1
    return [round(min_value + index * step, 6) for index in range(count)]


def _deterministic_random(*parts):
    """A stable random source so output never changes between runs."""
    return random.Random("|".join(str(part) for part in parts))


def write_lighting():
    rows = []
    for index, lat in enumerate(_grid(REGION_MIN_LAT, REGION_MAX_LAT, LIGHTING_GRID_STEP)):
        for column, lon in enumerate(
            _grid(REGION_MIN_LON, REGION_MAX_LON, LIGHTING_GRID_STEP)
        ):
            rng = _deterministic_random("lighting", lat, lon)
            status = rng.choices(LIGHTING_STATUSES, weights=LIGHTING_WEIGHTS, k=1)[0]
            observed = TODAY - timedelta(days=rng.randint(30, 540))
            rows.append(
                {
                    "segment_id": f"SIM-LGT-{index:03d}-{column:03d}",
                    "latitude": f"{lat:.6f}",
                    "longitude": f"{lon:.6f}",
                    "lighting_status": status,
                    "observation_date": observed.isoformat(),
                    "verification_status": "simulated",
                    "source": SIMULATED_SOURCE,
                }
            )

    path = DATA_DIR / "sample_lighting.csv"
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return len(rows)


def write_hazards():
    rows = []
    hazard_number = 0
    for index, lat in enumerate(_grid(REGION_MIN_LAT, REGION_MAX_LAT, HAZARD_GRID_STEP)):
        for column, lon in enumerate(
            _grid(REGION_MIN_LON, REGION_MAX_LON, HAZARD_GRID_STEP)
        ):
            rng = _deterministic_random("hazard", lat, lon)
            if rng.random() > HAZARD_PRESENCE_PROBABILITY:
                continue

            hazard_number += 1
            category = rng.choice(HAZARD_CATEGORIES)
            reported = TODAY - timedelta(days=rng.randint(1, 400))
            if rng.random() < 0.5:
                verification = "unverified_report"
            else:
                verification = "simulated"

            rows.append(
                {
                    "hazard_id": f"SIM-HZD-{hazard_number:04d}",
                    "latitude": f"{lat:.6f}",
                    "longitude": f"{lon:.6f}",
                    "category": category,
                    "description": (
                        f"Simulated {category.replace('_', ' ')} report near this "
                        "grid cell. No real incident is described."
                    ),
                    "reported_at": reported.isoformat(),
                    "verification_status": verification,
                    "source": SIMULATED_SOURCE,
                }
            )

    path = DATA_DIR / "sample_hazards.csv"
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return len(rows)


if __name__ == "__main__":
    lighting_count = write_lighting()
    hazard_count = write_hazards()
    print(f"Wrote {lighting_count} simulated lighting rows to sample_lighting.csv")
    print(f"Wrote {hazard_count} simulated hazard rows to sample_hazards.csv")
